services:
  backend-db:
    image: ${BACKEND_DB_IMAGE}
    env_file: .env
    environment:
      - POSTGRES_DB=${BACKEND_DB_NAME}
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
    ports:
      - ${BACKEND_DB_PORT}:5432
    volumes:
      - backend-db-data:/var/lib/postgresql/data

volumes:
  backend-db-data:
