services:
  backend-db:
    image: ${BACKEND_DB_IMAGE}
    env_file: .env
    environment:
      - POSTGRES_DB=${BACKEND_DB_NAME}
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
    ports:
      - ${BACKEND_DB_PORT}:5432
    volumes:
      - backend-db-data:/var/lib/postgresql/data

  bull-queue:
    image: redis:7.4.1-alpine
    restart: always
    env_file: .env
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${QUEUE_PASSWORD}
    volumes:
      - queue-data:/queue-data

volumes:
  backend-db-data:
  queue-data:
    driver: local
