/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type V1AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/register_controller.ts').default['store_web'], true>
}
type V1AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['store_web'], true>
}
type V1AuthValidGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['check'], false>
}
type V1AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/logout_controller.ts').default['handle'], false>
}
type V1SpaceCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/space.ts')['createSpace']>>
  response: MakeTuyauResponse<import('../app/controllers/spaces_controller.ts').default['create'], true>
}
type V1SpaceUploadPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/space.ts')['uploadToSpace']>>
  response: MakeTuyauResponse<import('../app/controllers/spaces_controller.ts').default['upload'], true>
}
type V1BranchIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/cells_controller.ts').default['allCells'], false>
}
type V1CellSavetitlePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/cell.ts')['saveTitle']>>
  response: MakeTuyauResponse<import('../app/controllers/cells_controller.ts').default['saveTitle'], true>
}
type V1CellSavecontentPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/cell.ts')['saveContent']>>
  response: MakeTuyauResponse<import('../app/controllers/cells_controller.ts').default['saveContent'], true>
}
type V1CellCreatenotePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/cell.ts')['createNote']>>
  response: MakeTuyauResponse<import('../app/controllers/cells_controller.ts').default['createNote'], true>
}
type V1CellDeletecellDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/cell.ts')['deleteCell']>>
  response: MakeTuyauResponse<import('../app/controllers/cells_controller.ts').default['deleteCell'], true>
}
export interface ApiDefinition {
  'v1': {
    'auth': {
      'register': {
        '$url': {
        };
        '$post': V1AuthRegisterPost;
      };
      'login': {
        '$url': {
        };
        '$post': V1AuthLoginPost;
      };
      'valid': {
        '$url': {
        };
        '$get': V1AuthValidGetHead;
        '$head': V1AuthValidGetHead;
      };
      'logout': {
        '$url': {
        };
        '$post': V1AuthLogoutPost;
      };
    };
    'space': {
      'create': {
        '$url': {
        };
        '$post': V1SpaceCreatePost;
      };
      'upload': {
        '$url': {
        };
        '$post': V1SpaceUploadPost;
      };
    };
    'branch': {
      ':branchId': {
        '$url': {
        };
        '$get': V1BranchIdGetHead;
        '$head': V1BranchIdGetHead;
      };
    };
    'cell': {
      'save_title': {
        '$url': {
        };
        '$post': V1CellSavetitlePost;
      };
      'save_content': {
        '$url': {
        };
        '$post': V1CellSavecontentPost;
      };
      'create_note': {
        '$url': {
        };
        '$post': V1CellCreatenotePost;
      };
      'delete_cell': {
        '$url': {
        };
        '$delete': V1CellDeletecellDelete;
      };
    };
  };
}
const routes = [
  {
    params: [],
    name: 'register.store.web',
    path: '/v1/auth/register',
    method: ["POST"],
    types: {} as V1AuthRegisterPost,
  },
  {
    params: [],
    name: 'login.store.web',
    path: '/v1/auth/login',
    method: ["POST"],
    types: {} as V1AuthLoginPost,
  },
  {
    params: [],
    name: 'login.check.web',
    path: '/v1/auth/valid',
    method: ["GET","HEAD"],
    types: {} as V1AuthValidGetHead,
  },
  {
    params: [],
    name: 'logout.store.web',
    path: '/v1/auth/logout',
    method: ["POST"],
    types: {} as V1AuthLogoutPost,
  },
  {
    params: [],
    name: 'space.create',
    path: '/v1/space/create',
    method: ["POST"],
    types: {} as V1SpaceCreatePost,
  },
  {
    params: [],
    name: 'space.upload',
    path: '/v1/space/upload',
    method: ["POST"],
    types: {} as V1SpaceUploadPost,
  },
  {
    params: ["branchId"],
    name: 'branch.allCells',
    path: '/v1/branch/:branchId',
    method: ["GET","HEAD"],
    types: {} as V1BranchIdGetHead,
  },
  {
    params: [],
    name: 'branch.save.title',
    path: '/v1/cell/save_title',
    method: ["POST"],
    types: {} as V1CellSavetitlePost,
  },
  {
    params: [],
    name: 'branch.save.content',
    path: '/v1/cell/save_content',
    method: ["POST"],
    types: {} as V1CellSavecontentPost,
  },
  {
    params: [],
    name: 'branch.create.note',
    path: '/v1/cell/create_note',
    method: ["POST"],
    types: {} as V1CellCreatenotePost,
  },
  {
    params: [],
    name: 'branch.delete.cell',
    path: '/v1/cell/delete_cell',
    method: ["DELETE"],
    types: {} as V1CellDeletecellDelete,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
