/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type V1AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/register_controller.ts').default['store_web'], true>
}
type V1AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['store_web'], true>
}
type V1AuthValidGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['check'], false>
}
type V1AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/logout_controller.ts').default['handle'], false>
}
type V1SpaceCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/space.ts')['createSpace']>>
  response: MakeTuyauResponse<import('../app/controllers/spaces_controller.ts').default['create'], true>
}
export interface ApiDefinition {
  'v1': {
    'auth': {
      'register': {
        '$url': {
        };
        '$post': V1AuthRegisterPost;
      };
      'login': {
        '$url': {
        };
        '$post': V1AuthLoginPost;
      };
      'valid': {
        '$url': {
        };
        '$get': V1AuthValidGetHead;
        '$head': V1AuthValidGetHead;
      };
      'logout': {
        '$url': {
        };
        '$post': V1AuthLogoutPost;
      };
    };
    'space': {
      'create': {
        '$url': {
        };
        '$post': V1SpaceCreatePost;
      };
    };
  };
}
const routes = [
  {
    params: [],
    name: 'register.store.web',
    path: '/v1/auth/register',
    method: ["POST"],
    types: {} as V1AuthRegisterPost,
  },
  {
    params: [],
    name: 'login.store.web',
    path: '/v1/auth/login',
    method: ["POST"],
    types: {} as V1AuthLoginPost,
  },
  {
    params: [],
    name: 'login.check.web',
    path: '/v1/auth/valid',
    method: ["GET","HEAD"],
    types: {} as V1AuthValidGetHead,
  },
  {
    params: [],
    name: 'logout.store.web',
    path: '/v1/auth/logout',
    method: ["POST"],
    types: {} as V1AuthLogoutPost,
  },
  {
    params: [],
    name: 'space.create',
    path: '/v1/space/create',
    method: ["POST"],
    types: {} as V1SpaceCreatePost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
