name: Deploy to dev env

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      USER: deploy
      HOST: ${{ secrets.SSH_HOST }}
      DIR: /home/deploy/releases
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: pnpm/action-setup@v4

      - name: Install dependencies step
        run: |
          pnpm i

      - name: Build step
        run: |
          pnpm build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          ssh -p 222 -o KexAlgorithms=curve25519-sha256@libssh.org -i ~/.ssh/id_rsa $USER@$HOST mkdir -p $DIR

      - name: Send backend to VPS
        run: |
          rsync -avvzP --whole-file --timeout=30 --no-perms --no-owner --no-group -e 'ssh -p 222 -i ~/.ssh/id_rsa -o KexAlgorithms=curve25519-sha256@libssh.org' apps/backend/build/ $USER@$HOST:$DIR/back-$GITHUB_SHA/

      - name: Send frontend to VPS
        run: |
          rsync -avvzP --whole-file --timeout=30 --no-perms --no-owner --no-group -e 'ssh -p 222 -i ~/.ssh/id_rsa -o KexAlgorithms=curve25519-sha256@libssh.org' apps/web/build/ $USER@$HOST:$DIR/front-$GITHUB_SHA/

      - name: Deploy
        run: |
          ssh -p 222 -o KexAlgorithms=curve25519-sha256@libssh.org -i ~/.ssh/id_rsa $USER@$HOST 'bash -s' < ./deploy.sh
