name: Deploy to dev env

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: pnpm/action-setup@v4

      - name: Install dependencies step
        run: |
          pnpm i

      - name: Build step
        run: |
          pnpm build

      - name: Deploy binary using rsync
        env:
          USER: deploy
          HOST: ${{ secrets.SSH_HOST }}
          DIR: /home/deploy/releases
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

          ssh -p 222 -o KexAlgorithms=curve25519-sha256@libssh.org -i ~/.ssh/id_rsa $USER@$HOST mkdir -p $DIR
          rsync -azP --no-perms --no-owner --no-group -e 'ssh -p 222 -i ~/.ssh/id_rsa -o KexAlgorithms=curve25519-sha256@libssh.org' apps/web/build/ $USER@$HOST:$DIR/front-$GITHUB_SHA/
          rsync -azP --no-perms --no-owner --no-group -e 'ssh -p 222 -i ~/.ssh/id_rsa -o KexAlgorithms=curve25519-sha256@libssh.org' apps/backend/build/ $USER@$HOST:$DIR/back-$GITHUB_SHA/

          ssh -p 222 -o KexAlgorithms=curve25519-sha256@libssh.org -i ~/.ssh/id_rsa $USER@$HOST "cd $DIR/back-$GITHUB_SHA && npm i --omit=dev"
          ssh -p 222 -o KexAlgorithms=curve25519-sha256@libssh.org -i ~/.ssh/id_rsa $USER@$HOST 'bash -s' < ./deploy.sh
