name: Deploy to dev env

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: pnpm/action-setup@v4

      - name: Install dependencies step
        run: |
          pnpm i

      - name: Build step
        run: |
          pnpm build
          cd apps/backend/build
          pnpm i --prod

      - name: Deploy binary using SCP
        env:
          USER: deploy
          HOST: ${{ secrets.SSH_HOST }}
          DIR: /home/deploy/releases
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

          ssh -vvv -p 222 -i ~/.ssh/id_rsa -o KexAlgorithms=curve25519-sha256@libssh.org $USER@$HOST echo "Test connection"

          # tar czvf front-$GITHUB_SHA.tar.gz apps/web/build
          # tar czvf back-$GITHUB_SHA.tar.gz apps/backend/build
          #
          # ssh -p 222 -i ~/.ssh/id_rsa $USER@$HOST mkdir -p $DIR
          # scp -P 222 -C -o ConnectTimeout=120 -o ServerAliveInterval=60 -i ~/.ssh/id_rsa front-$GITHUB_SHA.tar.gz $USER@$HOST:$DIR/
          # scp -P 222 -C -o ConnectTimeout=120 -o ServerAliveInterval=60 -i ~/.ssh/id_rsa back-$GITHUB_SHA.tar.gz $USER@$HOST:$DIR/
          # ssh -p 222 -i ~/.ssh/id_rsa $USER@$HOST 'bash -s' < ./deploy/deploy.sh
